# Sidebar navigation

- label: Getting Started
  items:
    - label: 'Installation'
      link: '/installation'
    - label: 'Project Setup & Configuration'
      link: '/project-setup'
    - label: 'Enhanced Input'
      link: '/project-setup/enhanced-input'
- label: Usage
  items:
    - label: 'Quick Start'
      link: '/usage/quick-start'
    - label: 'With Gameplay Tasks (w/o GAS)'
      link: '/usage/with-gameplay-tasks'
    - label: 'With Gameplay Abilities (with GAS)'
      link: '/usage/with-gameplay-abilities'
    - label: 'Auto Setup and Anim Notifiers'
      link: '/usage/auto-setup'
- label: Guides
  items:
    - label: 'Handling Collision'
      link: '/guides/collision'
    - label: 'Usage with AI'
      link: '/guides/ai'
- label: Gameplay Effects
  items:
    - label: 'Cost'
      link: '/gameplay-effects/cost'
    - label: 'Effect Containers'
      link: '/gameplay-effects/containers'
- label: Gameplay Cues
  items:
    - label: 'Gameplay Cues (SFX / VFX Hit Impacts)'
      link: '/gameplay-cues'
- label: Pages
  items:
    - label: 'Philosophy / Core Principles'
      link: '/pages/core-principles'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'Github'
      link: https://github.com/mklabs/ComboGraphDocs