# Sidebar navigation

- label: Getting Started
  items:
    - label: 'Installation'
      link: '/installation'
    - label: 'Project Setup & Configuration'
      link: '/project-setup'
    - label: 'Enhanced Input'
      link: '/project-setup/enhanced-input'
- label: Usage
  items:
    - label: 'Quick Start'
      link: '/usage/quick-start'
    - label: 'With Gameplay Tasks (w/o GAS)'
      link: '/usage/with-gameplay-tasks'
    - label: 'With Gameplay Abilities (with GAS)'
      link: '/usage/with-gameplay-abilities'
    - label: 'Auto Setup and Anim Notifiers'
      link: '/usage/auto-setup'
    - label: 'Usage with AI'
      link: '/guides/ai'
- label: Collision
  items:
    - label: 'Handling Collision'
      link: '/collision'
    - label: 'Plugin Integration: AGR Pro'
      link: '/collision/plugin-integration-agrpro'
    - label: 'Plugin Integration: Combat Components'
      link: '/collision/plugin-integration-combatcomponents'
- label: Gameplay Effects
  items:
    - label: 'Cost (with GAS)'
      link: '/gameplay-effects/cost'
    - label: 'Effect Containers (with GAS)'
      link: '/gameplay-effects/containers'
    - label: 'Damage Containers (w/o GAS)'
      link: '/gameplay-effects/damage-system'
- label: Gameplay Cues
  items:
    - label: 'Gameplay Cues (SFX / VFX Hit Impacts)'
      link: '/gameplay-cues'
- label: Graph
  items:
    - label: 'Conduit'
      link: '/graph/conduit'
    - label: 'Transition Behavior'
      link: '/graph/transition-behavior'
    # - label: 'Enhanced Input Triggers'
    #   link: '/graph/triggers'
    # - label: 'Combo Node Blueprint'
    #   link: '/graph/combo-node'
- label: Topics
  items:
    - label: 'Charge Attacks'
      link: '/topics/charge-attacks'
- label: Pages
  items:
    - label: 'Philosophy / Core Principles'
      link: '/pages/core-principles'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: Changelog
      link: /changelog
    - label: 'Github'
      link: https://github.com/combo-graph/documentation